### ISSUE TITLE
Chapter2 Section 2.5 example output img error

### ISSUE THREAD

**Issue by ecuplxd** [3dgen/cppwasm-book#13]
In the end of Chapter2 Section 2.5, the example output img error(It seems use the section 2.4.1 example)
https://3dgen.cn/cppwasm-book/zh/ch2-c-js/ch2-05-em-asm.html
![image](https://user-images.githubusercontent.com/7802753/64404809-ba011c80-d0af-11e9-89f0-00a6af97af7b.png)

**Comment by 3dgen** [comment]
thanks, already fixed.
