### ISSUE TITLE
《面向WebAssembly编程》源代码求助

### ISSUE THREAD

**Issue by cyk2018** [3dgen/cppwasm-book#20]
两位作者你们好：
最近在看这本书，里面没有提供源代码链接，部分章节和这个代码库的内容和example路径下的文件不对应，不知道作者大大有没有兴趣提供一个代码库链接方便同学们编译和运行。

**Comment by chai2010** [comment]
https://github.com/3dgen/cppwasm-book/tree/master/wasm-in-action-book-examples

**Comment by cyk2018** [comment]
收到，谢谢作者大大专程更新

**Comment by 3dgen** [comment]
由于 emcc 版本更新，某些代码可能无法正常使用。基本原理还是那些，例子仅作参考。

**Comment by cyk2018** [comment]
好的哈，我根据最新的版本编译测试部分指令，如果有更新，我根据最新版本提一个PR上来，感谢两位作者大大。反馈非常迅速。
