### ISSUE TITLE
两个c的库如何编译到自己的工程

### ISSUE THREAD

**Issue by 1312543912** [3dgen/cppwasm-book#3]
真的很开心有中国人在深入搞webassmebly，现在想请教一个问题：
我工程中有两个库a.h和b.h这两个都是第三方库，我现在又写了一个c.h引用了这两个库，并且都已经调通了，但是我在使用webassmebly打包c.h时候遇见了问题，我不知道如何让它找到a.h和b.h。
感谢您能回复。

**Comment by 3dgen** [comment]
如果是include路径的问题，emcc兼容大多数的gcc编译指令，可以在编译时增加"-I<inc_path>"的方式增加include路径，如：
-I../3rdParty/zlib/include

**Comment by 1312543912** [comment]
![image](https://user-images.githubusercontent.com/21102828/46784718-c8409e80-cd61-11e8-9f46-5b760c169d86.png)

我在opus2aac这个是我自己的写的胶接代码，是将a.h和b.h胶接在一起，而且a.h和b.h我也使用webassmebly搞定了，但是还会报这个错误。您如果有这方面经验，希望给我点建议

**Comment by 1312543912** [comment]
问题已经解决了，thanks。
