### ISSUE TITLE
抽奖送3本<WebAssembly标准入门>图书

### ISSUE THREAD

**Issue by chai2010** [3dgen/cppwasm-book#4]
## 抽奖链接

[https://github.com/3dgen/cppwasm-book/issues/4](https://github.com/3dgen/cppwasm-book/issues/4)

----

## <WebAssembly标准入门>相关链接：

- Github: https://github.com/chai2010/awesome-wasm-zh/blob/master/webassembly-primer.md
- 异步：[https://www.epubit.com/book/detail/40619](https://www.epubit.com/book/detail/40619)
- 豆瓣：[https://book.douban.com/subject/30396640/](https://book.douban.com/subject/30396640/)
- 京东：[https://item.jd.com/12499372.html](https://item.jd.com/12499372.html)

几个有意思的例子(基于asm.js)：

- 浏览器中的放大镜: https://chai2010.cn/awesome-wasm-zh/examples/hello-sdl/
- 浏览器跑C语言: https://chai2010.cn/awesome-wasm-zh/examples/c4/

----

## 公平公正的抽奖规则

抽奖规则的设计原则：

- 组织方和参与者均有参与感
- 抽奖的结果可重现，但是开奖之前无法预支结果

收集参与抽奖的人

- 必须有github账号，并在这个issue留言参与抽奖
- github账号必须2018年之前申请的
- 只接受大陆普通快递可达地区

抽奖的流程

1. 开始前，大家可以验证规则是否有缺陷，有任何问题都可以讨论
1. 我在抽奖正式开始时(可以提前参与)，会准备一个秘密的字符串作为种子，然后先公布种子字符串的MD5，同时公布截止的规则(可以是ID达到一个数量, 或者是设置一个截止时间里程碑)
1. 参与抽象的同学回复一个幸运字符串(`[0-9a-zA-Z-_]`等字符组成，1-32个字符)，也可以用自己的账号(如果用户如果担心泄密，也可以公布MD5)
1. 开奖前我公布作为种子的秘密字符串，大家可以验证MD5，以防止我作弊
1. 开奖前，参与者如果是提供MD5的也需要公布自己的幸运字符串，大家也去验证
1. 每个ID和秘密的种子字符串各生成一个对应的crc32数字，最后把数字加起来对人数取模就是中奖号
1. 每个ID作为utf8字符串排序，排序后的位置就是每个ID的抽奖号码
1. 在开奖后和结果公布之前，会锁定这个issue，之后会再重新打开
1. 抽完一个之后删除中奖ID，继续上述流程
1. 任何人可以验证结果

补充点：

- 有任何疑问请加入 QQ群 (726475047) 讨论
- 如果用户以MD5公布的幸运号，那么在抽奖截止后要公布真实的幸运号，否则作废
- 如果担心MD5不够安全，可以加盐，比如  `abc:sdfsd` 生成的MD5, abc是幸运号，冒号后面是salt
- 每个账号如果回复多个幸运字符串，以开奖前的最后一个为准
- chai2010和ending不参与

----

## 抽奖的代码(Go语言实现)

下面是抽奖算法的例子，种子字符串是wasm，2各参与者：

```go
// Copyright 2018 chaishushan@gmail.com. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"
	"hash/crc32"
	"sort"
)

func main() {
	luckyStar := MakeLuckyStar("wasm", map[string]string{
		"chai2010": "chai2010",
		"ending":   "ending",
	})

	fmt.Println(luckyStar)
	// output: ending
}

func MakeLuckyStar(seed string, luckyTokens map[string]string) string {
	var (
		crc32Sum   = uint64(crc32.ChecksumIEEE([]byte(seed)))
		sortedKeys = make([]string, 0, len(luckyTokens))
	)

	for id, tok := range luckyTokens {
		crc32Sum += uint64(crc32.ChecksumIEEE([]byte(tok)))
		sortedKeys = append(sortedKeys, id)
	}
	sort.Strings(sortedKeys)

	idx := int(crc32Sum) % len(luckyTokens)
	return sortedKeys[idx]
}
```

https://play.golang.org/p/mox2zhbde49

**Comment by zlus** [comment]
zlus

**Comment by z-jingjie** [comment]
重在参与！谢谢大神为WASM社区贡献作品~

**Comment by hoperuin** [comment]
gogogo

**Comment by yxwsbobo** [comment]
1

**Comment by oracle3** [comment]
没看懂

**Comment by 500646** [comment]
分母+`

**Comment by duobei** [comment]
+1

**Comment by qiushuiqs** [comment]
qiushuiqs

**Comment by logeable** [comment]
谢谢惠顾

**Comment by un-defined** [comment]
3

**Comment by chai2010** [comment]
合法的幸运字符串必须以 `[0-9a-zA-Z-_]` 等字符组成，长度为1-32个字符。
如果是不合法的幸运码，那么将用ID作为幸运码。

如果是不合法的幸运码，可以重新想一个，
最终以截止时间前最后一次回复为准。

**Comment by logeable** [comment]
A_A

**Comment by vfan** [comment]
jscoder

**Comment by happytoTom** [comment]
happytoTom

**Comment by zacklocx** [comment]
c++_forever

**Comment by zacklocx** [comment]
zacklocx

**Comment by Maopy** [comment]
maopy

**Comment by xbox1994** [comment]
niupi

**Comment by niucang** [comment]
niucang

**Comment by renji001** [comment]
v587

**Comment by gladmo** [comment]
前排参与，并看看抽奖代码

**Comment by litianjiao** [comment]
JoJo

**Comment by gladmo** [comment]
gladmo

**Comment by yyh1102** [comment]
lowesyang

**Comment by yohoj** [comment]
yohoj

**Comment by yangliyl** [comment]
yangliyl

**Comment by Deteriorator** [comment]
JustForFun

**Comment by YL2014** [comment]
YL2014

**Comment by chai2010** [comment]
种子字符串的 MD5 为: `1674409b850179fab3d35f400054ff79`

截止时间为 2018.12.31（根据情况可能提前截止，需要提前1周通知），参与的ID不超过100个。

开奖时我会公布字符串

**Comment by yunshang** [comment]
alshin

**Comment by Ir1d** [comment]
ir1dxd

**Comment by penghua123** [comment]
goodluck

**Comment by oracle3** [comment]
oracle3

**Comment by itstudying** [comment]
webassembly

**Comment by loohoo** [comment]
loohoo

**Comment by googya** [comment]
hoodoo

**Comment by yj21world** [comment]
yj

**Comment by thecorsair** [comment]
webassembly 😊

**Comment by sjtutyx** [comment]
Wasm走一走

**Comment by sjtutyx** [comment]
wasmjs

**Comment by Orangem21** [comment]
orange

**Comment by tinysniper** [comment]
赞！

**Comment by jeanary** [comment]
谢谢无私贡献，参与抽奖

**Comment by chai2010** [comment]
很多同学有点等不及提前下单了，因此我们也希望快点抽奖。
我目前想法是，下周三（2018.12.19）24:00前参与的有效，下周四公布种子字符串开奖（根据之前的规则提前一周通知）。

另外，有些回复中文的直接以id作为幸运码了，还有一个幸运码包含了`C++`中的加号不在有效字符中。
希望能将`+`符号也作为有效的字符。

大家如果有异议，在本周提出（直接回issue）。
如果没有异议，就按这个计划执行了。

最终开奖时，会给出完整的Go代码，大家自己运行验证。

**Comment by smartepsh** [comment]
py_trade

**Comment by zhmushan** [comment]
zhmushan

**Comment by shoukailiang** [comment]
goodliang

**Comment by CookiesEason** [comment]
cookiesEason

**Comment by woshidaxian** [comment]
nice

**Comment by JeoA** [comment]
yeah

**Comment by LinkXSystem** [comment]
will

**Comment by anheiqq** [comment]
aishing

**Comment by WXY1228** [comment]
postman

**Comment by Hurricane-Chen** [comment]
excited

**Comment by chai2010** [comment]
```
$ md5 -s ending-law:wasm
MD5 ("ending-law:wasm") = 1674409b850179fab3d35f400054ff79
```

种子字符串为: ending-law

**Comment by chai2010** [comment]
感谢大家的参与。一共收集到53个参与者，信息如下。
大家帮忙检查下是否有记录错误的，如果没有的话，就以此为准明天正式生效。

PS: 大家不要改前面的回复了，因为可能干扰最终结果。


```go
var luckyIdTable = map[string]string{
	"zlus":      "zlus",
	"z-jingjie": "z-jingjie",
	"hoperuin":  "gogogo",
	"yxwsbobo":  "1",
	//"oracle3":      "oracle3", // 无效幸运码, 用ID; 重复设置, 保留后一个
	"elvinn":         "elvinn",
	"500646":         "500646", // 无效幸运码, 用ID
	"duobei":         "+1",
	"qiushuiqs":      "qiushuiqs",
	"un-defined":     "3",
	"logeable":       "A_A",
	"vfan":           "jscoder",
	"happytoTom":     "happytoTom",
	"zacklocx":       "zacklocx",
	"Maopy":          "maopy",
	"xbox1994":       "niupi",
	"niucang":        "niucang",
	"renji001":       "v587",
	"litianjiao":     "JoJo",
	"gladmo":         "gladmo",
	"yyh1102":        "lowesyang",
	"yohoj":          "yohoj",
	"yangliyl":       "yangliyl",
	"Deteriorator":   "JustForFun",
	"YL2014":         "YL2014",
	"Noel1992":       "happy",
	"mrFranklin":     "20150308",
	"yunshang":       "alshin",
	"Ir1d":           "ir1dxd",
	"penghua123":     "goodluck",
	"oracle3":        "oracle3", // 覆盖之前的值
	"itstudying":     "webassembly",
	"loohoo":         "loohoo",
	"googya":         "hoodoo",
	"1124219777":     "lihail",
	"fqd511":         "511",
	"yj21world":      "yj",
	"thecorsair":     "webassembly",
	"sjtutyx":        "wasmjs",
	"Orangem21":      "orange",
	"tinysniper":     "tinysniper",
	"jeanary":        "jeanary",
	"SteveJiao":      "tell",
	"smartepsh":      "py_trade",
	"zhmushan":       "zhmushan",
	"shoukailiang":   "goodliang",
	"CookiesEason":   "cookiesEason",
	"woshidaxian":    "nice",
	"JeoA":           "yeah",
	"LinkXSystem":    "will",
	"anheiqq":        "aishing",
	"WXY1228":        "postman",
	"Hurricane-Chen": "excited",
	"vyf":            "vyf",
}
```

**Comment by chai2010** [comment]
取消了锁定，有问题尽快反馈。

如果没有疑问，明天就生效了。
生效之后，即使发现新的错误也不会再改了。

**Comment by chai2010** [comment]
恭喜以下三位同学：

```
1 yohoj
2 Orangem21
3 WXY1228
```

同时感谢所有的参与者，这是大家共同选择的结果。

希望上面3为同学给我发下邮寄地址（chaishushan@gmail.com），
或者加入 QQ群:726475047，给我发QQ消息

**Comment by chai2010** [comment]
@Orangem21 奖品已经处理

**Comment by chai2010** [comment]
感谢大家的参与，这个issue就关闭了。
近期如果有任何问题，依然可以在此留言

谢谢

**Comment by cifer-lee** [comment]
好可惜, 已经结束了
